DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS visits;
DROP TABLE IF EXISTS people;
DROP TABLE IF EXISTS webhook_clients;
DROP TABLE IF EXISTS static_devices;

CREATE TABLE people (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL, 
	macaddr TEXT NOT NULL
);

CREATE TABLE webhook_clients (
	url TEXT NOT NULL
);

CREATE TABLE static_devices (
	macaddr TEXT NOT NULL, 
	name TEXT,
	registrationtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	disconnectiontime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE visits (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	macaddr TEXT NOT NULL,
	name TEXT, 
	lastarrivaltime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastexittime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	timesseen INTEGER, 
	averagestay REAL
);

CREATE TABLE slice (
	datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	floor0 INTEGER, 
	floor1 INTEGER,
	floor2 INTEGER, 
	floor3 INTEGER
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);