DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS visits;
DROP TABLE IF EXISTS people;

CREATE TABLE people (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL, 
	macaddr TEXT NOT NULL
);

CREATE TABLE visits (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	macaddr TEXT NOT NULL,
	entrytime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	exittime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	route TEXT
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);